### ISSUE TITLE
Missing lass/5pkgs/drbd/default.nix file

### ISSUE THREAD

**Issue by wigust** [Mic92/stockholm#19]
Hello.

Could you share DRBD kernel module `lass/5pkgs/drbd/default.nix`, please?

https://github.com/Mic92/stockholm/blob/b726b7588d2dcf83507ed138723efed73efebe9f/lass/3modules/drbd.nix#L59

**Comment by Mic92** [comment]
cc @Lassulus

**Comment by Mic92** [comment]
Also this is a mirror of https://github.com/krebs/stockholm/

**Comment by Lassulus** [comment]
uh sure, I will push to krebs/stockholm

**Comment by Lassulus** [comment]
here you go: https://github.com/krebs/stockholm/commit/32b23666d15861f6f4d8b1f522ee53d4f21fabb6
